# wordpress-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      id: C0905650
      env: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        id: C0905650
        env: dev
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: mariadb.wordpress-db.svc.cluster.local 
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_DATABASE
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD
        volumeMounts:
          - name: wordpress-storage
            mountPath: /var/www/html
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  type: LoadBalancer  
  ports:
    - port: 80
  selector:
    app: wordpress
    id: C0905650
    env: dev


